version: '3.8'

services:
  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: mongodb://db:27017/estimationDB
    depends_on:
      - db

volumes:
  db_data:
